#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Run from the qube holding this repo, on the desktop. Each step says where
# the Owner types it: dom0, sys-net, sys-firewall, calendar-server, the
# router's admin page, or a qube on the laptop; nothing here reaches them by
# itself. Assumes Qubes OS 4.2 (nftables), the Calendar Server set up by
# scripts/setup-calendar-server.sh, and sys-net and sys-firewall as ordinary
# (not disposable) qubes. Addresses are saved to .env (git-ignored).

REPO=$(cd "$(dirname "$0")/.." && pwd)
cd "$REPO"
THIS_QUBE=$(qubesdb-read /name 2>/dev/null || hostname)
PORT=5232

# ip_number A.B.C.D prints the address as one number, to compare addresses.
ip_number() {
  local a b c d
  IFS=. read -r a b c d <<<"$1"
  printf '%s' $(((a << 24) + (b << 16) + (c << 8) + d))
}

# valid_ip A.B.C.D succeeds for a dotted IPv4 address.
valid_ip() {
  [[ "$1" =~ ^([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$ ]] || return 1
  local part
  for part in "${BASH_REMATCH[@]:1}"; do ((10#$part <= 255)) || return 1; done
}

# same_network A B PREFIX succeeds when A and B share the first PREFIX bits.
same_network() {
  local mask=$(((0xFFFFFFFF << (32 - $3)) & 0xFFFFFFFF))
  (( ($(ip_number "$1") & mask) == ($(ip_number "$2") & mask) ))
}

# ask_ip KEY "Prompt" asks until the answer is an IPv4 address.
ask_ip() {
  while true; do
    ask "$1" "$2"
    valid_ip "${!1}" && return
    warn "That is not an IPv4 address like 192.168.1.250. Try again."
  done
}

# copy_forward_script QUBE copies home-network/forward-caldav.sh into QUBE.
copy_forward_script() {
  say "This copies home-network/forward-caldav.sh (no secrets in it) into $1."
  note "If $1 has an older copy, remove it first: in $1, rm -f ~/QubesIncoming/$THIS_QUBE/forward-caldav.sh"
  say "A dom0 dialog will ask for the target qube: choose $1."
  if confirm "Run qvm-copy now?"; then
    qvm-copy "$REPO/home-network/forward-caldav.sh"
  else
    SKIPPED+=("copy home-network/forward-caldav.sh into $1 (qvm-copy)")
  fi
}

TOTAL_STAGES=13

banner "Calendar Server on the Home Network (issue #3)"

CALENDAR_SERVER_IP=$(_existing CALENDAR_SERVER_IP || true)
if [[ -z "$CALENDAR_SERVER_IP" ]]; then
  say "The Calendar Server's IP is not in $ENV_FILE yet (setup-calendar-server.sh saves it)."
  say "In dom0, run:  qvm-prefs calendar-server ip"
  ask_ip CALENDAR_SERVER_IP "Paste the IP it printed:"
  write_env CALENDAR_SERVER_IP "$CALENDAR_SERVER_IP"
fi

stage "dom0: check sys-net and sys-firewall"
say "In a dom0 terminal, run:"
step "qvm-prefs sys-net klass; qvm-prefs calendar-server netvm; qvm-prefs sys-firewall netvm"
note "Expect: AppVM, sys-firewall, sys-net."
if ! confirm "Did it print exactly AppVM, sys-firewall and sys-net?"; then
  warn "This procedure assumes the default sys-net <- sys-firewall <- calendar-server"
  warn "chain and a sys-net that keeps its /rw. A disposable sys-net forgets the"
  warn "fixed address and the forwarding on every start. Fix that first, then re-run."
  exit 1
fi
say "Now sys-firewall's IP, as sys-net sees it:"
step "qvm-prefs sys-firewall ip"
ask_ip SYS_FIREWALL_IP "Paste the IP it printed:"
write_env SYS_FIREWALL_IP "$SYS_FIREWALL_IP"

stage "sys-net: look up the Home Network connection"
say "Connect the desktop to the Home Network the way it normally is (cable or"
say "Wi-Fi). Open a terminal in sys-net (dom0: qvm-run sys-net xterm) and run:"
step "nmcli -f DEVICE,TYPE,STATE,CONNECTION device | grep -v -e '^vif' -e '^lo'"
step "ip -4 -br addr show scope global | grep -v '^vif'"
step "ip -4 route show default"
step "nmcli -g IP4.DNS device show \$(ip -4 route show default | awk '{print \$5; exit}')"
note "1st: the interface (DEVICE, e.g. wls6 or ens6) and its CONNECTION name"
note "     (e.g. 'Wired connection 1' or the Wi-Fi's name)."
note "2nd: its current address, e.g. 192.168.1.37/24; the number after / is the prefix."
note "3rd: 'default via <router's address>'.   4th: the DNS server(s)."
ask SYS_NET_INTERFACE "Interface (DEVICE column):"
ask SYS_NET_CONNECTION "Connection name (CONNECTION column):"
ask LAN_PREFIX "Prefix length (the number after /, usually 24):"
ask_ip LAN_GATEWAY "Router's address (after 'default via'):"
ask LAN_DNS "DNS server(s), separated by spaces:"
write_env SYS_NET_INTERFACE "$SYS_NET_INTERFACE"
write_env SYS_NET_CONNECTION "$SYS_NET_CONNECTION"
write_env LAN_PREFIX "$LAN_PREFIX"
write_env LAN_GATEWAY "$LAN_GATEWAY"
write_env LAN_DNS "$LAN_DNS"

stage "Router: find the DHCP range and pick the desktop's fixed address"
say "Open the router's admin page in a browser in any qube:"
step "http://$LAN_GATEWAY/"
note "Log in with the router's admin password (often printed on the router)."
say "Find the DHCP server settings, usually under LAN, Local Network or DHCP."
say "Note the first and last address it hands out (the pool or range)."
ask_ip DHCP_FIRST "First address of the DHCP range:"
ask_ip DHCP_LAST "Last address of the DHCP range:"
write_env DHCP_FIRST "$DHCP_FIRST"
write_env DHCP_LAST "$DHCP_LAST"
planned=$(_existing HOME_NETWORK_IP || true)
[[ -n "$planned" ]] && note "setup-calendar-server.sh recorded $planned as the planned address."
say "Choose the desktop's fixed address: on $LAN_GATEWAY/$LAN_PREFIX's network,"
say "outside $DHCP_FIRST to $DHCP_LAST, and not the router's own address."
while true; do
  ask_ip DESKTOP_LAN_IP "The desktop's fixed Home Network address:"
  n=$(ip_number "$DESKTOP_LAN_IP")
  if ((n >= $(ip_number "$DHCP_FIRST") && n <= $(ip_number "$DHCP_LAST"))); then
    warn "$DESKTOP_LAN_IP is inside the DHCP range: the router could hand it to another device."
  elif [[ "$DESKTOP_LAN_IP" == "$LAN_GATEWAY" ]]; then
    warn "That is the router's own address."
  elif ! same_network "$DESKTOP_LAN_IP" "$LAN_GATEWAY" "$LAN_PREFIX"; then
    warn "$DESKTOP_LAN_IP is not on the router's network ($LAN_GATEWAY/$LAN_PREFIX)."
  else
    break
  fi
done
write_env DESKTOP_LAN_IP "$DESKTOP_LAN_IP"
say "Check nothing on the Home Network uses it already. In sys-net:"
step "ping -c 3 -W 1 $DESKTOP_LAN_IP"
note "Expect 100% packet loss. If something answers, re-run and choose another address."
pause "Press Enter once nothing answered."

stage "Router: nothing forwarded from the internet"
say "Still in the router's admin page, check each of these:"
step "Port forwarding / Virtual servers / NAT rules: none points at $DESKTOP_LAN_IP,"
step "  at the desktop's current DHCP address, or at port $PORT. Delete any you find."
step "DMZ / Exposed host: off."
step "UPnP / NAT-PMP: off (it lets software on the Home Network open ports itself)."
step "IPv6 firewall, if the router has IPv6: inbound connections blocked (the default)."
note "The router needs no change for the Calendar Server: the Home Network already"
note "reaches the desktop directly."
pause "Press Enter once the router forwards nothing to the desktop."

stage "sys-net: give the desktop its fixed address"
say "In the sys-net terminal, run:"
step "sudo nmcli connection modify '$SYS_NET_CONNECTION' ipv4.method manual ipv4.addresses $DESKTOP_LAN_IP/$LAN_PREFIX ipv4.gateway $LAN_GATEWAY ipv4.dns '$LAN_DNS'"
step "sudo nmcli connection up '$SYS_NET_CONNECTION'"
say "Check it took, and that it is saved where Qubes keeps it across restarts:"
step "ip -4 -br addr show $SYS_NET_INTERFACE"
step "nmcli -g ipv4.method,ipv4.addresses,ipv4.gateway,ipv4.dns,connection.filename connection show '$SYS_NET_CONNECTION'"
step "ls /rw/config/NM-system-connections/"
step "ping -c 2 $LAN_GATEWAY && getent hosts qubes-os.org"
note "Expect $DESKTOP_LAN_IP/$LAN_PREFIX; manual, the address, gateway and DNS, and a file in"
note "/etc/NetworkManager/system-connections/, which Qubes keeps in /rw/config/NM-system-connections"
note "(listed by ls); replies from the router; an address for qubes-os.org."
warn "The fixed address belongs to this connection: on another Wi-Fi network it does not apply."
pause "Press Enter once all of that looked right."

stage "sys-net: forward only port $PORT to sys-firewall"
copy_forward_script sys-net
say "In the sys-net terminal, run:"
step "sudo sh ~/QubesIncoming/$THIS_QUBE/forward-caldav.sh sys-net --lan $DESKTOP_LAN_IP/$LAN_PREFIX --interface $SYS_NET_INTERFACE --to $SYS_FIREWALL_IP --install"
step "sudo nft list chain ip qubes caldav-dnat; tail -n 1 /rw/config/qubes-firewall-user-script"
note "Expect 'Forwarding TCP $PORT ...', one rule '... tcp dport $PORT counter ... dnat to $SYS_FIREWALL_IP',"
note "and the user script ending in a call to /rw/config/forward-caldav.sh,"
note "which Qubes runs on every start of sys-net."
pause "Press Enter once it looked like that."

stage "sys-firewall: forward only port $PORT to calendar-server"
copy_forward_script sys-firewall
say "Open a terminal in sys-firewall (dom0: qvm-run sys-firewall xterm) and run:"
step "sudo sh ~/QubesIncoming/$THIS_QUBE/forward-caldav.sh sys-firewall --lan $DESKTOP_LAN_IP/$LAN_PREFIX --to $CALENDAR_SERVER_IP --install"
step "sudo nft list chain ip qubes caldav-dnat; cat /rw/config/qubes-firewall-user-script"
note "Expect one rule '... tcp dport $PORT counter ... dnat to $CALENDAR_SERVER_IP'. The user script"
note "keeps the rules earlier wizards added (qubes allowed to reach the Calendar"
note "Server) and now ends in a call to /rw/config/forward-caldav.sh."
pause "Press Enter once it looked like that."

stage "calendar-server: accept port $PORT"
say "install.sh already opened port $PORT, and only it, in calendar-server."
say "Check in a calendar-server terminal (dom0: qvm-run calendar-server xterm):"
step "sudo nft list chain ip qubes custom-input"
note "Expect exactly one rule: tcp dport $PORT ct state new accept."
note "If it is missing, re-run install.sh as in the next stage: it adds it."
pause "Press Enter once it is there."

renewed=no
stage "calendar-server: a certificate naming $DESKTOP_LAN_IP"
say "Devices on the Home Network reach the Calendar Server at $DESKTOP_LAN_IP, so"
say "the certificate must name it, or they refuse it. In calendar-server:"
step "openssl x509 -in ~/radicale/secrets/server.crt -noout -ext basicConstraints,subjectAltName"
if confirm "Does it list IP Address:$DESKTOP_LAN_IP, and not CA:TRUE?"; then
  say "It does already: nothing to change, and no Device has to re-trust it."
  pause
else
  renewed=yes
  say "Re-make it. First copy the newer install files."
  note "If calendar-server has an older copy, remove it first: in calendar-server, rm -rf ~/QubesIncoming/$THIS_QUBE/calendar-server"
  say "A dom0 dialog will ask for the target qube: choose calendar-server."
  if confirm "Run qvm-copy now?"; then
    qvm-copy "$REPO/calendar-server"
  else
    SKIPPED+=("copy calendar-server/ into the calendar-server qube (qvm-copy)")
  fi
  say "Then, in calendar-server:"
  step "bash ~/QubesIncoming/$THIS_QUBE/calendar-server/install.sh --name $CALENDAR_SERVER_IP --name $DESKTOP_LAN_IP --renew-certificate"
  note "Add one more --name for any other IP Address the openssl command listed."
  note "The password and the Calendar are kept; it asks for the password once."
  pause "Press Enter once it printed 'Done.'"
fi

stage "Devices: trust the new certificate"
if [[ "$renewed" == no ]]; then
  say "The certificate did not change: nothing to do here."
  pause
else
  warn "Every Device that trusted the old certificate refuses the Calendar Server"
  warn "until it has the new one."
  say "1. The desktop's Calendar Qube. In calendar-server, run this and choose calendar:"
  step "qvm-copy ~/radicale/secrets/server.crt"
  note "   (If calendar has an older copy, first: in calendar, rm -f ~/QubesIncoming/calendar-server/server.crt)"
  say "   Then, in calendar:"
  step "install -m 644 ~/QubesIncoming/calendar-server/server.crt ~/.config/vdirsyncer/server.crt && calendar-sync && echo SYNC OK"
  say "2. Thunderbird, in calendar: quit Thunderbird, then run"
  step "bash ~/QubesIncoming/$THIS_QUBE/calendar-qube/install-thunderbird.sh --server https://$CALENDAR_SERVER_IP:$PORT/ --certificate ~/.config/vdirsyncer/server.crt"
  note "   If calendar-qube/ is gone from QubesIncoming, from $THIS_QUBE: qvm-copy $REPO/calendar-qube"
  note "   Start Thunderbird: the Calendar shows, with no certificate warning."
  say "3. Any qube you ran the Sync check from: copy server.crt there again the same way."
  say "4. The phone (DAVx5) and the laptop's Calendar Qube, if already set up, need it too."
  pause "Press Enter once calendar printed SYNC OK and Thunderbird shows the Calendar."
fi

stage "Laptop: run the Sync check over the Home Network"
say "On the laptop, on the Home Network, open a terminal in any qube with network"
say "access (e.g. a disposable). Get the Sync check:"
step "curl -fsSLO https://raw.githubusercontent.com/moraisgabri/personal-calendar/main/src/personal_calendar/sync_check.py"
say "Fetch the Calendar Server's certificate over the Home Network:"
step "openssl s_client -connect $DESKTOP_LAN_IP:$PORT </dev/null 2>/dev/null | openssl x509 > server.crt"
step "openssl x509 -in server.crt -noout -fingerprint -sha256"
say "On the desktop, in calendar-server, print the real one's fingerprint:"
step "openssl x509 -in ~/radicale/secrets/server.crt -noout -fingerprint -sha256"
warn "The two fingerprints must be identical. If not, stop: something else answered."
say "Then, on the laptop:"
step "python3 sync_check.py https://$DESKTOP_LAN_IP:$PORT/ --user owner --certificate server.crt"
note "It asks for the Owner's password and must end with 'Sync check passed.'"
note "If it can't connect: in sys-net, sudo nft list table ip qubes, and see which"
note "caldav counter stayed at 0; then the same in sys-firewall."
pause "Press Enter once it passed."

stage "Laptop: nothing else is reachable"
say "In the same laptop qube, try other ports on the desktop:"
step "for p in 22 80 443 631 8080 $PORT; do timeout 3 bash -c \"</dev/tcp/$DESKTOP_LAN_IP/\$p\" 2>/dev/null && echo \"\$p OPEN\" || echo \"\$p closed\"; done"
note "Expect every port closed except '$PORT OPEN'."
say "From the internet: on the phone, turn Wi-Fi off (mobile data only). Find the"
say "home's public address on the router's status page (or: curl -s https://api.ipify.org"
say "in a desktop qube) and open https://<public address>:$PORT/ in the phone's browser."
note "Expect it to time out or fail to connect. The router forwards nothing, so this"
note "double-checks the router; it is not the protection itself."
pause "Press Enter once only $PORT was open and the internet could not connect."

stage "Reboot the desktop, then check again"
say "Last, prove it all survives a restart. This wizard ends here; the next"
say "screen shows what to run once the desktop is back."
pause "Press Enter for that list."

finish
printf '%s  After rebooting the desktop:%s\n' "$BOLD" "$RESET"
step "Reboot the desktop, log in, wait a minute for calendar-server to start."
step "On the laptop, in the same qube as before:"
step "  python3 sync_check.py https://$DESKTOP_LAN_IP:$PORT/ --user owner --certificate server.crt"
note "Expect 'Sync check passed.' If not: in sys-net, ip -4 -br addr shows $DESKTOP_LAN_IP?"
note "sudo nft list table ip qubes | grep caldav lists the chains? Then the same in sys-firewall."
printf '\n'
