#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Run on the desktop, from the qube holding this repo. The phone can't run a
# script, so this shows each phone step and waits; docs/phone.md is the same
# procedure as a checklist. Commands marked "dom0" or "calendar-server" are
# typed by the Owner in a terminal of that qube.
# Assumes the Calendar Server reachable on the Home Network at DESKTOP_LAN_IP
# (scripts/setup-home-network.sh) and the desktop Calendar Qube
# (scripts/setup-calendar-qube.sh), whose khal is the other Device in the checks.

REPO=$(cd "$(dirname "$0")/.." && pwd)
cd "$REPO"
QUBE=calendar
DAY=2030-01-04

TOTAL_STAGES=11

banner "GrapheneOS phone Syncing with the Calendar Server (issue #4)"

DESKTOP_LAN_IP=$(_existing DESKTOP_LAN_IP || true)
if [[ -z "$DESKTOP_LAN_IP" ]]; then
  say "The desktop's fixed Home Network address is not in $ENV_FILE yet"
  say "(scripts/setup-home-network.sh saves it as DESKTOP_LAN_IP)."
  ask DESKTOP_LAN_IP "The desktop's Home Network address, e.g. 192.168.1.5:"
  write_env DESKTOP_LAN_IP "$DESKTOP_LAN_IP"
fi
URL="https://$DESKTOP_LAN_IP:5232/"

stage "calendar-server: the certificate's fingerprint"
say "The phone will be shown the Calendar Server's certificate once. You trust it"
say "only if its fingerprint matches this one, read on the desktop itself."
say "In a calendar-server terminal (dom0: qvm-run calendar-server xterm), run:"
step "openssl x509 -in ~/radicale/secrets/server.crt -noout -fingerprint -sha256 -ext subjectAltName"
note "The subjectAltName must list IP Address:$DESKTOP_LAN_IP. If not, stop and re-run"
note "scripts/setup-home-network.sh, which re-makes the certificate."
say "Copy the part after 'sha256 Fingerprint=' (Ctrl-Shift-C there, Ctrl-Shift-V here)."
ask CERTIFICATE_SHA256 "Paste the fingerprint:"
CERTIFICATE_SHA256=$(printf '%s' "$CERTIFICATE_SHA256" | sed 's/.*=//' | tr 'a-f' 'A-F' | tr -d ' ')
write_env CERTIFICATE_SHA256 "$CERTIFICATE_SHA256"
note "Not a secret: it only identifies the certificate. Saved so re-runs show it."

stage "Phone: install F-Droid, DAVx⁵ and Fossify Calendar"
step "In Vanadium, open https://f-droid.org and tap Download F-Droid; install it,"
step "allowing Vanadium to install apps when Android asks (then turn that back off)."
step "Open F-Droid and let it update its repositories."
step "In F-Droid, search and install DAVx⁵ (by bitfire web engineering)."
step "In F-Droid, search and install Fossify Calendar."
note "No Play Store or Google services are involved."
pause "Press Enter once both apps are installed."

stage "Phone: let DAVx⁵ and Fossify Calendar run in the background"
step "Open DAVx⁵. On its introduction screens, at 'Regular sync intervals', allow it to"
step "run in the background (Android asks to stop optimizing its battery: Allow)."
step "At 'Tasks support' tick 'I don't need tasks support.' and continue."
step "At 'Permissions', turn on 'Calendar permissions', 'Notification permission',"
step "'Local network permission' (if listed) and 'Keep permissions'. Leave Contacts off."
step "Android Settings > Apps > DAVx⁵ > App battery usage: Allow background usage, Unrestricted."
step "Android Settings > Apps > Fossify Calendar > App battery usage: the same, so reminders fire on time."
note "Names can differ slightly between Android versions; look for battery usage."
pause "Press Enter once both are Unrestricted."

stage "Phone: add the Calendar Server to DAVx⁵ (accept the certificate once)"
step "In DAVx⁵, tap + (Add account) > 'Login with URL and user name'."
step "Base URL:  $URL"
step "User name: owner     Password: the Owner's Calendar password (password manager)"
step "Tap Login. DAVx⁵ shows the unknown certificate. Under FINGERPRINTS, the line"
step "starting 'SHA256:' must equal, pair by pair:"
printf '\n      %s%s%s\n\n' "$BOLD" "$CERTIFICATE_SHA256" "$RESET"
step "Only if every pair matches: tick 'I have manually verified the whole fingerprint.' > Accept."
warn "If it differs, tap Reject: the phone did not reach the Calendar Server itself."
step "Account name: 'Calendar Server' (leave Contact group method as it is) > Add account."
step "Open the new account, CalDAV tab: tick the Calendar ('calendar')."
note "DAVx⁵ remembers the certificate; it won't ask again unless it changes."
pause "Press Enter once the Calendar is ticked."

stage "Phone: sync settings in DAVx⁵"
step "In the account, ⋮ > Account settings:"
step "  Calendars sync. interval: Every 15 minutes  (the shortest Android allows)"
step "  Sync over WiFi only: on"
step "  WiFi SSID restriction: your Home Network's Wi-Fi name, exactly as shown in Wi-Fi settings"
note "The SSID restriction needs Location, 'Allow all the time', for DAVx⁵; it then"
note "doesn't even try to Sync away from home. If you'd rather not give DAVx⁵ that"
note "permission, leave it blank: the next stage keeps failures quiet anyway."
pause "Press Enter once set."

stage "Phone: Sync failures don't flood"
say "When the desktop is off, DAVx⁵ can't connect; it reports that in its"
say "'Network and I/O errors' notification channel. Turn that channel off:"
step "DAVx⁵ > ☰ (menu) > Settings > Notification settings  (or Android Settings > Apps > DAVx⁵ > Notifications)"
step "Turn off 'Network and I/O errors'."
step "Leave 'Synchronization errors' on: it reports real problems, like a wrong password."
pause "Press Enter once 'Network and I/O errors' is off."

stage "Phone: show the Calendar in Fossify Calendar"
step "Open Fossify Calendar > ⋮ > Settings > turn on 'CalDAV sync'."
step "Allow it access to calendars, then tick 'calendar' (account 'Calendar Server') > OK."
step "Allow 'Alarms & reminders' when it asks: 'You must allow the app to schedule alarms for reminders to work properly.'"
note "Optional, GrapheneOS: Settings > Apps > Fossify Calendar > turn off Network."
note "It never needs the network; DAVx⁵ does the Syncing."
pause "Press Enter once the Calendar's events show in Fossify Calendar."

stage "Check: an event made on the phone reaches the desktop"
step "In Fossify Calendar, add an event on $DAY at 10:00 titled 'From the phone'."
step "In DAVx⁵, open the account and tap Synchronize now."
say "On the desktop, in a $QUBE terminal (dom0: qvm-run $QUBE xterm), run:"
step "calendar-sync && khal list $DAY 1d"
note "Expect 'From the phone'."
pause "Press Enter once khal lists it."

stage "Check: an event made elsewhere reaches the phone"
say "In the $QUBE terminal, run:"
step "khal new $DAY 12:00 13:00 'From the desktop' && calendar-sync"
step "On the phone, in DAVx⁵ tap Synchronize now, then open $DAY in Fossify Calendar."
note "Expect 'From the desktop' next to 'From the phone'."
pause "Press Enter once the phone shows it."

stage "Check: offline on the phone"
step "Turn on airplane mode (Wi-Fi off too)."
step "Fossify Calendar still shows $DAY with both events."
step "Add an event starting 5 minutes from now titled 'Reminder test', with a reminder"
step "'At start of event' (or 1 minute before). Lock the phone and wait: the reminder fires."
step "Still offline, rename 'From the phone' to 'Edited offline'."
step "Turn airplane mode off, back on the Home Network Wi-Fi. In DAVx⁵ tap Synchronize now."
say "Then, in the $QUBE terminal:"
step "calendar-sync && khal list $DAY 1d && khal list today 1d"
note "Expect 'Edited offline' (not 'From the phone') and 'Reminder test'."
pause "Press Enter once the reminder fired and the offline edit reached khal."

stage "Check: the Calendar Server off doesn't flood the phone"
say "In a calendar-server terminal, stop the Calendar Server:"
step "sudo systemctl stop radicale.service"
step "On the phone, in DAVx⁵, tap Synchronize now two or three times."
note "Expect no notification (DAVx⁵ may show a short sync error inside its own app: fine)."
step "Fossify Calendar still shows every event."
say "Start the Calendar Server again:"
step "sudo systemctl start radicale.service"
step "In DAVx⁵ tap Synchronize now: it succeeds again."
pause "Press Enter once that looked right."
say "Remove the test events: delete 'Edited offline', 'From the desktop' and"
say "'Reminder test' in Fossify Calendar, tap Synchronize now in DAVx⁵, then in $QUBE:"
step "calendar-sync && khal list $DAY 1d"
note "If they were the Calendar's only events, run  vdirsyncer sync --force-delete calendar  instead."
pause "Press Enter once the list is empty."

finish
