#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Run from the qube holding this repo. Commands marked "dom0" are typed by the
# Owner in a dom0 terminal; nothing here can reach dom0 by itself.
# Assumes Qubes OS 4.2, the Calendar Server set up by
# scripts/setup-calendar-server.sh, and a Fedora-based template.
# Only public values (qube names, the Backup key's public half) go to .env.

REPO=$(cd "$(dirname "$0")/.." && pwd)
cd "$REPO"
THIS_QUBE=$(qubesdb-read /name 2>/dev/null || hostname)
DRILL=calendar-restore-drill

# copy_files QUBE FOLDER copies a repo folder plus backup.py into QUBE.
copy_files() {
  local qube="$1" folder="$2"
  say "This copies the repo's $folder/ folder and backup.py (no secrets in them)."
  note "If $qube has older copies, remove them first: in $qube,"
  note "  rm -rf ~/QubesIncoming/$THIS_QUBE/$folder ~/QubesIncoming/$THIS_QUBE/backup.py"
  say "A dom0 dialog will ask for the target qube: choose $qube."
  if confirm "Run qvm-copy now?"; then
    qvm-copy "$REPO/$folder" "$REPO/src/personal_calendar/backup.py"
  else
    SKIPPED+=("copy $folder/ and backup.py into $qube (qvm-copy)")
  fi
}

# setup_stages create the vault qube, the dom0 policy and the schedule, and
# check each of them.
setup_stages() {
  stage "Template: install age"
  say "Both calendar-server and the vault qube need age. In dom0, find the template:"
  step "qvm-prefs calendar-server template"
  say "Open a terminal in that template (dom0: qvm-run <template> xterm) and run:"
  step "sudo dnf install -y age"
  say "Then, in dom0, shut the template down and restart calendar-server:"
  step "qvm-shutdown --wait <template> && qvm-shutdown --wait calendar-server && qvm-start calendar-server"
  note "The Calendar Server is back within a minute; Devices just Sync a little later."
  pause "Press Enter once calendar-server is running again."

  stage "dom0: create the vault qube, with no network"
  say "In a dom0 terminal, run:"
  step "qvm-create --class AppVM --label black $VAULT_QUBE"
  step "qvm-prefs $VAULT_QUBE netvm ''"
  step "qvm-prefs $VAULT_QUBE netvm"
  note "The last command must print nothing: the vault qube has no network at all."
  note "It uses the default template; it must be the one age was installed in"
  note "(check: qvm-prefs $VAULT_QUBE template)."
  note "Use a qube of its own, not your existing 'vault': if calendar-server were"
  note "ever compromised, the only thing it can reach is this qube's Backups."
  pause "Press Enter once netvm printed nothing."

  stage "Copy the vault files into $VAULT_QUBE"
  copy_files "$VAULT_QUBE" backup-vault

  stage "$VAULT_QUBE: install the vault and make the Backup key"
  say "Open a terminal in $VAULT_QUBE (dom0: qvm-run $VAULT_QUBE xterm) and run:"
  step "bash ~/QubesIncoming/$THIS_QUBE/backup-vault/install.sh"
  say "It prints the Backup key's public half, age1... Copy it with the Qubes"
  say "clipboard (Ctrl+C, then Ctrl+Shift+C in $VAULT_QUBE; Ctrl+Shift+V, then Ctrl+V here)."
  ask BACKUP_PUBLIC_KEY "Paste the public key (age1...):"
  while [[ ! "$BACKUP_PUBLIC_KEY" =~ ^age1[0-9a-z]+$ ]]; do
    warn "That is not an age public key; it starts with age1."
    ask BACKUP_PUBLIC_KEY "Paste the public key (age1...):"
  done
  write_env BACKUP_PUBLIC_KEY "$BACKUP_PUBLIC_KEY"
  note "The public key can only make Backups, not read them, so it is fine in .env."

  stage "Keep one offline copy of the Backup key"
  say "If the desktop is lost, the Backups are useless without the private key."
  say "In the $VAULT_QUBE terminal, show it:"
  step "cat ~/backup-key.txt"
  say "Write the AGE-SECRET-KEY-1... line on paper (check it twice), or save it"
  say "to an encrypted USB stick, and keep that away from the desktop."
  warn "Never copy it to another qube, into this repo, or into a chat."
  note "To restore with that copy: put the line in a file, e.g. backup-key.txt,"
  note "and give it to: backup.py restore ... --identity backup-key.txt"
  pause "Press Enter once the offline copy is made and put away."

  stage "dom0: allow only Backup delivery to $VAULT_QUBE"
  say "dom0 can't paste from other qubes, so type this file in dom0:"
  step "sudo nano /etc/qubes/policy.d/30-calendar-backup.policy"
  say "with exactly these three lines (columns separated by spaces):"
  printf '\n    personal-calendar.Backup  *  calendar-server  %s  allow\n' "$VAULT_QUBE"
  printf '    personal-calendar.Backup  *  @anyvm           @anyvm  deny\n'
  printf '    *                         *  calendar-server  %s  deny\n\n' "$VAULT_QUBE"
  note "Line 1: calendar-server may deliver Backups to $VAULT_QUBE."
  note "Line 2: no other qube may use the service. Line 3: calendar-server may do"
  note "nothing else with $VAULT_QUBE (no file copies, no other services)."
  note "The repo's backup-vault/30-calendar-backup.policy explains it too."
  pause "Press Enter once saved (Ctrl+O, Enter, Ctrl+X in nano)."

  stage "Copy the Backup files into calendar-server"
  copy_files calendar-server calendar-server

  stage "calendar-server: schedule Backups to $VAULT_QUBE"
  say "In a calendar-server terminal (dom0: qvm-run calendar-server xterm), run:"
  step "bash ~/QubesIncoming/$THIS_QUBE/calendar-server/install-backups.sh --vault $VAULT_QUBE --recipient $BACKUP_PUBLIC_KEY"
  note "Copy that line over with the Qubes clipboard rather than typing the key."
  note "It ends with: Backup calendar-....age delivered to $VAULT_QUBE."
  pause "Press Enter once it printed 'Done.'"
  say "Check it arrived. In the $VAULT_QUBE terminal:"
  step "ls -l ~/backups"
  pause "Press Enter once you see one calendar-....age file."

  stage "Check that only calendar-server can deliver Backups"
  say "From this qube ($THIS_QUBE), asking $VAULT_QUBE for the service must be refused:"
  answer=$(qrexec-client-vm "$VAULT_QUBE" personal-calendar.Backup+calendar-20000101T000000Z.age \
    </dev/null 2>&1 || true)
  if grep -q "refused" <<<"$answer"; then
    printf '  %s✓ refused, as it should be%s\n' "$GREEN" "$RESET"
  else
    warn "It was NOT refused ($answer): check the dom0 policy file before going on."
    SKIPPED+=("the dom0 policy did not refuse $THIS_QUBE; fix it and re-check")
  fi
  say "Then, in the calendar-server terminal, a file copy to $VAULT_QUBE must fail too:"
  step "qvm-copy-to-vm $VAULT_QUBE /etc/hostname"
  note "Expect 'Request refused' and no dialog."
  pause "Press Enter once it was refused."

  stage "Check that a failed Backup is noticed"
  say "In the calendar-server terminal, make one scheduled run fail on purpose:"
  step "mv ~/.config/calendar-backup/settings ~/.config/calendar-backup/settings.off"
  step "systemctl --user start calendar-backup.service"
  note "Expect a 'Calendar Backup failed' notification on the desktop, and"
  note "systemctl to report that the job failed."
  step "cat ~/BACKUP-FAILED.txt"
  pause "Press Enter once you saw the notification and the file."
  say "Put it back, and run it again:"
  step "mv ~/.config/calendar-backup/settings.off ~/.config/calendar-backup/settings"
  step "systemctl --user start calendar-backup.service && ls ~/BACKUP-FAILED.txt"
  note "Expect 'No such file': the warning goes away once a Backup works."
  pause "Press Enter once the warning was gone."

  stage "Check that Backups run by themselves"
  say "In dom0, restart calendar-server:"
  step "qvm-shutdown --wait calendar-server && qvm-start calendar-server"
  say "Wait 6 minutes, then in a new calendar-server terminal:"
  step "systemctl --user list-timers calendar-backup.timer"
  say "and in the $VAULT_QUBE terminal:"
  step "ls -l ~/backups"
  note "Expect a recent LAST run on the timer, and a new Backup in the vault."
  pause "Press Enter once both looked right."
}

# drill_stages restore the latest Backup into a fresh Calendar Server, in a
# throwaway qube, and prove it with the Sync check. Repeat it now and then.
drill_stages() {
  stage "$VAULT_QUBE: decrypt the latest Backup"
  say "In the $VAULT_QUBE terminal, run:"
  step "python3 /usr/local/lib/personal-calendar/backup.py restore \"\$(ls ~/backups/calendar-*.age | tail -n 1)\" ~/restore-drill --identity ~/backup-key.txt"
  step "find ~/restore-drill -name '*.ics' | wc -l"
  say "Compare with the Calendar Server, in a calendar-server terminal:"
  step "find ~/radicale/collections -name '*.ics' | wc -l"
  note "The numbers match unless events were added or deleted since the Backup."
  pause "Press Enter once the restore worked and the numbers look right."

  stage "dom0: a fresh qube for the Calendar Server"
  say "In dom0, run:"
  step "qvm-create --class AppVM --label red $DRILL"
  step "qvm-start $DRILL"
  step "qvm-prefs $DRILL ip"
  ask DRILL_IP "Paste the IP that the last command printed:"
  say "Now the install files and the Sync check. A dom0 dialog asks for the target: choose $DRILL."
  if confirm "Run qvm-copy now?"; then
    qvm-copy "$REPO/calendar-server" "$REPO/src/personal_calendar/sync_check.py"
  else
    SKIPPED+=("copy calendar-server/ and sync_check.py into $DRILL (qvm-copy)")
  fi

  stage "$DRILL: install a fresh Calendar Server"
  say "Open a terminal in $DRILL (dom0: qvm-run $DRILL xterm) and run:"
  step "bash ~/QubesIncoming/$THIS_QUBE/calendar-server/install.sh --name $DRILL_IP"
  note "It asks you to choose a password: any one will do, this qube is thrown away."
  pause "Press Enter once it printed 'Done.'"
  say "In the $VAULT_QUBE terminal, send it the restored Calendar and choose $DRILL:"
  step "qvm-copy ~/restore-drill"
  note "This copies the decrypted Calendar out of the vault, only to $DRILL."
  pause "Press Enter once copied."

  stage "$DRILL: restore, then run the Sync check"
  say "In the $DRILL terminal, put the restored Calendar in place:"
  step "sudo systemctl stop radicale && rm -rf ~/radicale/collections && cp -r ~/QubesIncoming/$VAULT_QUBE/restore-drill ~/radicale/collections && sudo systemctl start radicale"
  step "grep -rh '^SUMMARY' ~/radicale/collections | sort | head -20"
  note "Expect the titles of your own events."
  say "Then run the Sync check against it, with the password chosen for $DRILL:"
  step "python3 ~/QubesIncoming/$THIS_QUBE/sync_check.py https://$DRILL_IP:5232/ --user owner --certificate ~/radicale/secrets/server.crt"
  note "It must end with 'Sync check passed.'"
  pause "Press Enter once it passed."
  say "Clean up. In the $VAULT_QUBE terminal:"
  step "rm -rf ~/restore-drill"
  say "And in dom0:"
  step "qvm-shutdown --wait $DRILL && qvm-remove -f $DRILL"
  pause "Press Enter once both are gone."
}

printf '\n%s  Scheduled Backups into the vault qube%s\n\n' "$BOLD" "$RESET"
DRILL_ONLY=no
if confirm "Is everything set up already, and you only want the restore drill?"; then
  DRILL_ONLY=yes
  TOTAL_STAGES=4
else
  TOTAL_STAGES=15
fi

banner "Scheduled Backups into the vault qube (issue #8)"

VAULT_QUBE=$(_existing VAULT_QUBE || true)
if [[ -z "$VAULT_QUBE" ]]; then
  ask VAULT_QUBE "Name for the vault qube [Enter: calendar-vault]:"
  VAULT_QUBE=${VAULT_QUBE:-calendar-vault}
  write_env VAULT_QUBE "$VAULT_QUBE"
fi

[[ "$DRILL_ONLY" == yes ]] || setup_stages
drill_stages

finish
