#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Run from the qube holding this repo. Commands marked "dom0" are typed by the
# Owner in a dom0 terminal; nothing here can reach dom0 by itself.
# Assumes Qubes OS 4.2, the Calendar Server set up by
# scripts/setup-calendar-server.sh, and a Fedora-based template.

REPO=$(cd "$(dirname "$0")/.." && pwd)
cd "$REPO"
THIS_QUBE=$(qubesdb-read /name 2>/dev/null || hostname)
QUBE=calendar

TOTAL_STAGES=6

banner "Desktop Calendar Qube (issue #5)"

CALENDAR_SERVER_IP=$(_existing CALENDAR_SERVER_IP || true)
if [[ -z "$CALENDAR_SERVER_IP" ]]; then
  say "The Calendar Server's IP is not in $ENV_FILE yet (setup-calendar-server.sh saves it)."
  say "In dom0, run:  qvm-prefs calendar-server ip"
  ask CALENDAR_SERVER_IP "Paste the IP it printed:"
  write_env CALENDAR_SERVER_IP "$CALENDAR_SERVER_IP"
fi

stage "dom0: create the Calendar Qube"
say "In a dom0 terminal, run:"
step "qvm-create --class AppVM --label purple $QUBE"
step "qvm-start $QUBE"
step "qvm-prefs $QUBE ip"
note "It keeps internet access until the install is done (stage 5 locks it down)."
note "The qube uses your default template; it must be Fedora-based (check: qvm-prefs $QUBE template)."
ask CALENDAR_QUBE_IP "Paste the IP that the last command printed:"
write_env CALENDAR_QUBE_IP "$CALENDAR_QUBE_IP"

stage "sys-firewall: allow $QUBE to reach the Calendar Server"
say "Open a terminal in sys-firewall (dom0: qvm-run sys-firewall xterm) and run:"
rule="nft add rule ip qubes custom-forward ip saddr $CALENDAR_QUBE_IP ip daddr $CALENDAR_SERVER_IP tcp dport 5232 ct state new accept"
step "grep -qxF '$rule' /rw/config/qubes-firewall-user-script || echo '$rule' | sudo tee -a /rw/config/qubes-firewall-user-script"
step "sudo chmod +x /rw/config/qubes-firewall-user-script"
step "sudo $rule"
note "The first two lines make the rule survive restarts; the last applies it now."
pause "Press Enter once all three commands ran without errors."

stage "Copy the install files and the certificate into $QUBE"
say "This copies the repo's calendar-qube/ folder (no secrets in it)."
say "A dom0 dialog will ask for the target qube: choose $QUBE."
if confirm "Run qvm-copy now?"; then
  qvm-copy "$REPO/calendar-qube"
else
  SKIPPED+=("copy calendar-qube/ into $QUBE (qvm-copy)")
fi
say "Now the certificate. In a calendar-server terminal, run this and choose $QUBE:"
step "qvm-copy ~/radicale/secrets/server.crt"
pause "Press Enter once copied."

stage "$QUBE: install the Calendar"
say "Open a terminal in $QUBE (dom0: qvm-run $QUBE xterm) and run:"
step "bash ~/QubesIncoming/$THIS_QUBE/calendar-qube/install.sh --server https://$CALENDAR_SERVER_IP:5232/ --certificate ~/QubesIncoming/calendar-server/server.crt"
note "It asks for the Owner's Calendar password (from your password manager)"
note "and saves it in $QUBE, readable only by you there."
pause "Press Enter once it printed 'Done.'"

stage "dom0: let $QUBE reach only the Calendar Server"
say "In dom0, run:"
step "qvm-firewall $QUBE reset"
step "qvm-firewall $QUBE del accept"
step "qvm-firewall $QUBE add accept dsthost=$CALENDAR_SERVER_IP proto=tcp dstports=5232"
step "qvm-firewall $QUBE add drop"
step "qvm-firewall $QUBE list"
note "The list must show exactly two rules: accept to $CALENDAR_SERVER_IP port 5232, then drop."
note "To update khal or vdirsyncer later, open it up again with: qvm-firewall $QUBE reset"
pause "Press Enter once the list looks like that."

stage "$QUBE: check the Calendar"
say "In the $QUBE terminal, run each line:"
step "calendar-sync && echo SYNC OK"
step "curl --max-time 5 -sS https://example.org >/dev/null && echo 'INTERNET OPEN (wrong)' || echo 'internet blocked (right)'"
step "khal new 2030-01-01 10:00 11:00 'Calendar Qube test' && calendar-sync && khal list 2030-01-01 1d"
step "systemctl --user list-timers calendar-sync.timer"
note "Expect: SYNC OK, internet blocked, the test event listed, and the timer scheduled."
pause "Press Enter once all four checks looked right."
say "Remove the test event, here and on the Calendar Server:"
step "rm \$(grep -l 'Calendar Qube test' ~/.local/share/calendar/events/*.ics) && vdirsyncer sync --force-delete calendar && khal list 2030-01-01 1d"
note "--force-delete is needed only because the test event was the Calendar's"
note "only event: vdirsyncer won't empty the Calendar Server on its own."
note "Expect the test event to be gone from the list."
pause "Press Enter once it is gone."
say "Prove the Sync timer starts by itself. In dom0, run:"
step "qvm-shutdown --wait $QUBE && qvm-start $QUBE"
say "Then, after a minute, in a new $QUBE terminal:"
step "systemctl --user list-timers calendar-sync.timer"
pause "Press Enter once it shows a recent LAST run."

finish
